# Deployment definition for API pods

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-seed
  labels:
    app: api-seed
spec:
  template:
    metadata:
      labels:
        app: api-seed
    spec:
      containers:
      - name: api-seed
        image: adubeniuk/api-seed:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        ports:
        - name: api
          containerPort: 8080
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec curl http://$POD_IP:8080/users/1
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec curl http://$POD_IP:8080/users/1
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
